// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glzbuqufddikuqksrmxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsemJ1cXVmZGRpa3Vxa3NybXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjY4NDQsImV4cCI6MjA2Mzg0Mjg0NH0.50xQWlKeNNu5oj9DZz07HPHrbD3KVMEcNykUwrrRNys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);